hschain-PoW/HSChain/PoW/Consensus.hs, hschain-PoW/test/TM/Consensus.hs, hschain-control/HSChain/Control/Channels.hs, hschain-control/hschain-control.cabal
1. Add directional composable channels `Src`/`Sink`
2. Move BlockDb from Consensus (it never) changes
3. Add `asHeader` function
=> Add directional channels & updates to PoW types

hschain-crypto/hschain-crypto.cabal, hschain-examples/test/TM/Integration.hs, hschain-examples/test/TM/Validators.hs, nix/config.nix, nix/containers.nix, nix/default.nix, nix/derivations/ghc84/tasty.nix, nix/derivations/ghc86/tasty.nix, nix/derivations/ghc88/tasty.nix, nix/overrides.nix, nix/release.nix, nix/shell.nix
This is part of hunt for the #587. It seems that some builds crash and some don't preserving tests is thus important to be able to reproduce fault
- There're few unrelated tweaks in tests
- We use cryptonite by default. Mostly in order to rule out problems with libsodium bindings
=> Store test executables in nix artifacts

hschain-PoW/HSChain/PoW/Exceptions.hs, hschain-PoW/HSChain/PoW/Store/Internal/Query.hs, hschain/HSChain/Exceptions.hs, hschain/HSChain/Store/Internal/Query.hs
Core of the problem is banal use-after-free. sqlite's database's handle is
allocated by malloc and if we use handle after close we are modifying memory
owned by malloc, possibly overweriting malloc's data structures and causeing all
sort of mischief. It manifested itself in many ways:
- SQLite sometimes detected API misuse (#594)
- Sometimes malloc detected corruption of its structures
- Sometimes we get plain segfault
Use after free is caused by data race when thread using connection receives
exception and aborts _after_ database is closed. In addition runConcurrently
waits for all child threads when it terminates when one of its child threads
terminates for whatever reason. But if it is aborted by exception it doesn't
and this opens way for races.
Proposed fix is very simple: check …
=> Finally fix mysterious memory corrpution #587, #594

hschain-PoW/HSChain/Examples/Simple.hs, hschain-PoW/HSChain/PoW/Consensus.hs, hschain-PoW/HSChain/PoW/Logger.hs, hschain-PoW/HSChain/PoW/P2P.hs, hschain-PoW/HSChain/PoW/P2P/Handler/PEX.hs, hschain-PoW/HSChain/PoW/P2P/Handler/Peer.hs, hschain-PoW/HSChain/PoW/P2P/Types.hs, hschain-PoW/HSChain/PoW/Store/Internal/Query.hs, hschain-PoW/HSChain/PoW/Types.hs, hschain-examples/HSChain/Mock/Types.hs, hschain-merkle/HSChain/Types/Merkle/Tree.hs, hschain-merkle/HSChain/Types/Merkle/Types.hs, hschain-merkle/test/TM/MerkleBlock.hs, hschain-quickcheck/HSChain/Arbitrary/Instances.hs, hschain-types/HSChain/Types/Blockchain.hs, hschain/HSChain/Store.hs, hschain/HSChain/Store/Internal/BlockDB.hs, hschain/HSChain/Store/STM.hs
Idea is to factor out hash from three data types:
> IdNode | OptNode | Hashed
and replace it
> Hash · (Identity | Maybe | Proxy)
Kind and instance contexts become much simpler as result. In hindsight it's
obvious solution to the point: how could one do it differently?!
Idea due to @thesz
=> Refactor hschain-merkle

hschain-PoW/HSChain/Examples/Simple.hs, hschain-PoW/HSChain/PoW/Consensus.hs, hschain-PoW/HSChain/PoW/P2P.hs, hschain-PoW/HSChain/PoW/P2P/Handler/Consensus.hs, hschain-PoW/HSChain/PoW/P2P/Handler/Peer.hs, hschain-PoW/HSChain/PoW/P2P/Types.hs, hschain-PoW/HSChain/PoW/Types.hs, hschain-PoW/exe/pow-node.hs, hschain-PoW/test/TM/P2P.hs, hschain-PoW/test/TM/Util/Mockchain.hs
This PR all prerequisites for working with time and adjustments of mining difficulty, And miscellaneous bug fixes/improvements
- Time field is added to GBlock
- Header validation takes time parameter. It's needed in order to reject blocks from the future (not implemented yet)
- `BH` data type is moved to `HSChain.PoW.Types` since we need to pass ancestor chain to the block validation in order to compute difficulty adjustments
- `RxMined` message added as an optimization. This way mined block is processed atomically and node doesn't proceed to ask other nodes about freshly mined block they obviously don't have
- Block is forced to WHNF in `sendNewBlock`
- Peer sends announce immediately on connection which enables immediate sync
=> Preparation for time handling in PoW blockchain

hschain-PoW/HSChain/Examples/Simple.hs, hschain-PoW/HSChain/Examples/Util.hs, hschain-PoW/HSChain/PoW/P2P.hs, hschain-PoW/HSChain/PoW/P2P/Handler/Consensus.hs, hschain-PoW/HSChain/PoW/Types.hs, hschain-PoW/exe/pow-node.hs, hschain-PoW/test/TM/Consensus.hs, hschain-PoW/test/TM/P2P.hs, hschain-PoW/test/TM/Util/Mockchain.hs
Now KV example uses simple bitcoin-like work function (SHA256 of block) and
difficult adjustment algorithm copied from bitcoin as well.
NOTE TM.P2P.testCatchup is broken by this change but these tests need some
rework anyway
=> Implement difficulty adjustment for the KV node

cabal.project, hschain-examples-types/HSChain/Mock/Coin/Types.hs, hschain-examples-types/HSChain/Mock/Dioxane/Types.hs, hschain-examples-types/LICENSE, hschain-examples-types/Setup.hs, hschain-examples-types/hschain-examples-types.cabal, hschain-examples/HSChain/Mock/Coin.hs, hschain-examples/HSChain/Mock/Dioxane.hs, hschain-examples/hschain-examples.cabal, nix/overrides.nix, nix/release.nix
This is to allow build of -types package with GHCJS. Split is rather awkward since we have to pull blockchain logic along with type declarations
=> Split examples into examples and -types package

hschain-examples/HSChain/Mock.hs, hschain-examples/HSChain/Mock/Coin.hs, hschain-examples/HSChain/Mock/Dioxane.hs, hschain-examples/HSChain/Mock/KeyVal.hs, hschain-examples/exe/coin-node.hs, hschain-examples/exe/dioxane-node.hs, hschain-examples/test/TM/Integration.hs, hschain-examples/test/TM/P2P/PEX.hs, hschain-examples/test/TM/Validators.hs, hschain/HSChain/Control.hs
Attempt to play with row type emulation in haskell ended up in predicatable failure. When we try to look up value by its type we need to know type exactly but it breaks down when type is polymorphic (`Foo a`) for some a. It required explicit type annotations which make thing quite awkward to use. 
Another reason to abandon `:*:` is new hchain-config. Instances derived using this library interact with instance `:*:` rather poorly
=> Drop experiements with row polymorphism 

hschain-types/HSChain/Types/Blockchain.hs, hschain-types/HSChain/Types/Validators.hs, hschain/HSChain/Blockchain/Internal/Engine/Types.hs, hschain/HSChain/Blockchain/Internal/Types.hs
Notable changes: PrivValidator is moved to hschain-types to validator's public key.
=> Small tweaks for hschain

hschain-PoW/HSChain/Examples/Simple.hs, hschain-PoW/HSChain/PoW/Node.hs
Export Cfg from HSChain.PoW.Node
Do not return Target from adjustPuzzle:   
1) it's not used
2) it could be calculated from block if needed
3) only existing instance returns dummy value
=> Small tweaks to PoW code

hschain-PoW/HSChain/PoW/Consensus.hs, hschain-PoW/HSChain/PoW/Node.hs, hschain-PoW/hschain-PoW.cabal, hschain-PoW/test/Main.hs, hschain-PoW/test/TM/Consensus.hs, hschain-PoW/test/TM/P2P.hs, hschain-PoW/test/TM/Store.hs, hschain-PoW/test/TM/Util/Mockchain.hs, hschain-db/HSChain/Store/Query.hs
This PR adds both database-backed storage for blocks and extend in order accommodate future restoration of state from database:
- Function for fetching headers
- Functions for building block index  & finding better heads. 
Also adds tests for storage
=> Add block storage backed by database

hschain-PoW/HSChain/PoW/Consensus.hs, hschain-PoW/HSChain/PoW/P2P/Handler/Consensus.hs
```
$ jq -C < logs/node-2.log 'select(.msg=="New head")|{at,msg,data}'
...
{
"at": "2020-07-28T16:05:03.931059783Z",
"msg": "New head",
"data": {
"bid": "BoUMYNSqWJsvnPN1HbsDWzi4fCpCAdkZiTw4DCuuiUo6",
"h": 26
}
}
{
"at": "2020-07-28T16:05:03.931059783Z",
"msg": "New head",
"data": {
"bid": "HBYjNvZeTw2F5Y8DYtbrEcsC9G7rxz5qp6nnSEBic7qy",
"h": 27
}
...
```
=> Add better logging to PoW

hschain-PoW/HSChain/Examples/Coin.hs, hschain-PoW/HSChain/Examples/Simple.hs, hschain-PoW/HSChain/PoW/BlockIndex.hs, hschain-PoW/HSChain/PoW/Consensus.hs, hschain-PoW/HSChain/PoW/Node.hs, hschain-PoW/HSChain/PoW/Store.hs, hschain-PoW/HSChain/PoW/Types.hs, hschain-PoW/hschain-PoW.cabal, hschain-examples/HSChain/Mock/Coin.hs
Motivations is to break dependency loops when (so far nonexitent) mempool depends on BlockDB and Consensus depends on mempool
=> Move BlockIndex & BlockDB into separate modules

hschain-examples/HSChain/Mock/Coin.hs, hschain-examples/HSChain/Mock/Dioxane.hs, hschain-examples/HSChain/Mock/KeyVal.hs, hschain-examples/test/TM/Mempool.hs, hschain-examples/test/TM/Validators.hs, hschain-mempool/HSChain/Mempool.hs, hschain-mempool/hschain-mempool.cabal, hschain/HSChain/Internal/Types/Consensus.hs, hschain/HSChain/P2P.hs, hschain/HSChain/P2P/Internal.hs
Instead of using plain hash pass transaction id as parameter. Needed for PoW
where TID is data family
=> Reparametrize mempool

hschain-control/HSChain/Control/Via.hs, hschain-control/hschain-control.cabal, hschain-logger/HSChain/Logger.hs, hschain-logger/HSChain/Logger/Class.hs, nix/derivations/haskell/generic-lens-core.nix, nix/derivations/haskell/indexed-profunctors.nix, nix/derivations/haskell/microlens.nix, nix/overrides.nix
This is an attempt to improve logging. 
- Newtype wrappers for derivingvia for mtl's type classes are added to hschain-control
- StdoutLogT & new StdoutLogNoNamespaceT could be used with deriving via
=> Improve StdoutLogT

hschain-PoW/HSChain/Examples/Simple.hs, hschain-PoW/HSChain/PoW/Consensus.hs, hschain-PoW/exe/coin-node.hs, hschain-PoW/test/TM/Util/Mockchain.hs
Turns out this is required for the DB-backed state storage since we need to
find path between state recorded in DB and current overlay and we need access to
block index for that
=> Add state 

hschain-examples/HSChain/Mock/Coin.hs, hschain-examples/hschain-examples.cabal, hschain-examples/test/Main.hs, hschain-examples/test/TM/Coin.hs, hschain-examples/test/TM/Util/MockChain.hs
Short: query condition in`dbLookupUTXO` was wrong so double spend transaction was provisionally accepted and consequent write crashed due to constraint violations. Also PR contains:
1. Tests for coin state transitions
2. Orphans for working with database using coin types
=> Fix bug in coin's state hadnling which caused crash on double spend

hschain-db/HSChain/Store/Query.hs
Add ability to avoid fetching all data from prepared queries. API is in style of hybrid of unfoldr/scanl. It come in two variant one that allows to stop early and another which allows to stop early and provides last element at the same time
=> Extend prepared queries

hschain-examples/HSChain/Mock/Types.hs, hschain-examples/test/TM/Util/Network.hs, hschain-mempool/HSChain/Mempool.hs, hschain/HSChain/Internal/Types/Config.hs, hschain/HSChain/P2P.hs, hschain/HSChain/P2P/Internal.hs, hschain/HSChain/Run.hs, notebook/hschain/logs.py
As it turns out old mempool gossip (try to send TX every N ms) is completely unusable at high througput. So obvious solution is to try to send TX as soon as we accepted one in the mempool. Downside of new scheme is that we won't send txs that already in the mempool to freshly connected peer. But that should be handled separately.
This PR restores collection of mempool stats as well
=> Allow mempool to be used at hight throughput and restore mempool stat

hschain-crypto/HSChain/Crypto/Classes/Hash.hs
It allows to compute hash of value from supplied builder. Default implementation
is provided but more efficient implementation is thinkable
=> Add method to CryptoHash type class

hschain-PoW/HSChain/PoW/API.hs, hschain-PoW/HSChain/PoW/Node.hs, hschain-PoW/exe-test/run-pow.sh, hschain-PoW/exe/coin-key.hs, hschain-PoW/exe/coin-node.hs, hschain-PoW/hschain-PoW.cabal
This PR adds basic API which allows to query node over HTTP for following:
- Ask balances of keys
- Ask to generate unsigned transaction 
- Post signed transaction 
It add program for working with keys and signing transactions. Keys are stored in plain text in the yaml file. Not terribly secure but suitable for testing when one have to work with multiple keys at once
=> Add rest API for coin PoW node

hschain-PoW/HSChain/PoW/Consensus.hs, hschain-PoW/HSChain/PoW/P2P/Handler/Consensus.hs, hschain-PoW/test/TM/Consensus.hs
Propagate errors in mined block's state. This is very useful for testing and debugging of mining algorithms
Also make logging slightly more informative
=> Report errors processing of mined's block state

hschain-PoW/HSChain/Examples/Coin.hs, hschain-PoW/HSChain/Examples/Simple.hs, hschain-PoW/HSChain/PoW/Consensus.hs, hschain-PoW/HSChain/PoW/Node.hs, hschain-PoW/HSChain/PoW/Store.hs, hschain-PoW/HSChain/PoW/Types.hs, hschain-PoW/exe/coin-node.hs, hschain-PoW/test/TM/Store.hs, hschain-PoW/test/TM/Util/Mockchain.hs
- Lenses for Block are added
- Newtype for time difference is added
- BlockException is type family now
- Block construtor is rename to `Block`
- `thresholdRetarget` method dropped
- `runNode` is not used anymore and dropped
Block mining needs further rework. For example block creation function may need extra parameters like coinbase transaction etc. trying to encode them in BlcokData type class is pain so it's left as future work
=> Samll rework of BlockData type class

hschain-merkle/HSChain/Types/Merkle/Tree.hs, hschain-merkle/test/TM/MerkleBlock.hs
- Add type class as generic API for working with proofs of inclusion
- Add nonempty tree variant
- Add serialie instaces
- Rename BlockTree -> BinTree
=> Rework merkle trees

hschain-PoW/HSChain/Examples/Coin.hs, hschain-PoW/HSChain/Examples/Simple.hs, hschain-PoW/HSChain/PoW/Consensus.hs, hschain-PoW/HSChain/PoW/Mempool.hs, hschain-PoW/HSChain/PoW/Node.hs, hschain-PoW/HSChain/PoW/P2P.hs, hschain-PoW/HSChain/PoW/P2P/Handler/Consensus.hs, hschain-PoW/HSChain/PoW/P2P/Handler/PEX.hs, hschain-PoW/HSChain/PoW/P2P/Handler/Peer.hs, hschain-PoW/HSChain/PoW/P2P/Types.hs, hschain-PoW/HSChain/PoW/Store.hs, hschain-PoW/HSChain/PoW/Tests.hs, hschain-PoW/HSChain/PoW/Types.hs, hschain-PoW/exe/coin-light.hs, hschain-PoW/exe/coin-node.hs, hschain-PoW/hschain-PoW.cabal, hschain-PoW/test/TM/Consensus.hs, hschain-PoW/test/TM/Mempool.hs, hschain-PoW/test/TM/P2P.hs, hschain-PoW/test/TM/Store.hs, hschain-PoW/test/TM/Util/Mockchain.hs
This PR implements light node which only fetches headers and relies on full nodes for complete block validation. Supproting changes:
- Block database allows to store headers
- Fixed bug in block fetching when unsuccessful fetch means that block will never be fetched from another node. 
- Refactoring of internal APIs. `view` doesn't leak into network layer. Necessary for light node which doesn't have blockchain state
=> Implement light node

hschain-PoW/exe/coin-node.hs, hschain-PoW/test/TM/Util/Mockchain.hs, hschain-crypto-bls/tests/TM/BLS.hs, hschain-crypto/HSChain/Crypto.hs, hschain-crypto/test/TM/Crypto.hs, hschain-examples/HSChain/Mock/KeyList.hs, hschain-quickcheck/HSChain/Arbitrary/Instances.hs, hschain-types/test/TM/Time.hs
Practice showed that it's not used in normal code and only appear in
testing. And testing harness can very well have one more constraint
=> use ByteRepr instead of BYtereprSized superclass constraint
