hschain-net/HSChain/Network/Mock.hs
hschain/HSChain/P2P/Internal.hs

This is hack to make running testing more pleasant. Tasty insists on printing
exceptions in threads failing due to them. But threads failing due to network
exception is pretty normal and expected thing in our program. So we convert
NetworkError/MockNetError to ThreadKilled so it will dutyfully kill thread.
Loss of exception type is not important since we don't use it anyway
Also throw proper exception in mock network

Silence tasty's spam bout threads tragically dying

---

hschain/HSChain/Store/Internal/BlockDB.hs
hschain/HSChain/Store/Internal/Query.hs

Cache for ValidatorSet

---

hschain-PoW/HSChain/PoW/Consensus.hs
hschain-PoW/HSChain/PoW/P2P.hs
hschain-PoW/HSChain/PoW/P2P/Handler/BlockRequests.hs
hschain-PoW/HSChain/PoW/P2P/Handler/CatchupLock.hs
hschain-PoW/HSChain/PoW/P2P/Handler/Consensus.hs
hschain-PoW/HSChain/PoW/P2P/Handler/PEX.hs
hschain-PoW/HSChain/PoW/P2P/STM/PeerRegistry.hs
hschain-PoW/HSChain/PoW/P2P/Types.hs
hschain-PoW/test/TM/P2P.hs
hschain-control/HSChain/Control/Class.hs

Most notably:
1. Self connection are now handled correctly. Earlier we overwrote status on disconnect
2. Now we supply initial seeds to PEX
3. Logging improvements

Fixes for PoW

---

hschain-PoW/HSChain/Examples/Simple.hs
hschain-PoW/HSChain/PoW/P2P.hs
hschain-PoW/HSChain/PoW/P2P/Handler/Consensus.hs
hschain-PoW/HSChain/PoW/P2P/Handler/PEX.hs
hschain-PoW/HSChain/PoW/P2P/Handler/Peer.hs
hschain-PoW/HSChain/PoW/Types.hs
hschain-PoW/exe/pow-node.hs
hschain-PoW/hschain-PoW.cabal
hschain-PoW/test/TM/P2P.hs

Add node. It doesn't really work. Node are able to establish connection between themselves and send messages but for some reason are not able to download blocks.
Also improve logging

Draft of PoW node

---

hschain-PoW/HSChain/PoW/P2P/Handler/PEX.hs
hschain-PoW/HSChain/PoW/P2P/Handler/Peer.hs
hschain-PoW/HSChain/PoW/P2P/Types.hs
hschain-PoW/exe/pow-node.hs

Problem was we did not release lock in all cases which caused peer to never send more than one (or few if it got lucky) request.
Also improve logging

Fix block propagation

---

hschain-PoW/HSChain/Examples/Simple.hs
hschain-PoW/HSChain/PoW/Consensus.hs
hschain-PoW/HSChain/PoW/Types.hs

Since we don't store work in block and calculate it Naturl seems ot be quite
natural fit
Per @thesz suggestion

Make Work are newtype of Natural

---

hschain-PoW/HSChain/Examples/Util.hs
hschain-PoW/HSChain/PoW/Consensus.hs
hschain-PoW/HSChain/PoW/P2P.hs
hschain-PoW/HSChain/PoW/P2P/Handler/Consensus.hs
hschain-PoW/HSChain/PoW/P2P/Handler/Peer.hs
hschain-PoW/HSChain/PoW/P2P/Types.hs
hschain-PoW/HSChain/PoW/Types.hs
hschain-PoW/exe/noin-pow-node.hs
hschain-PoW/exe/pow-node.hs
hschain-PoW/hschain-PoW.cabal
hschain-PoW/test/TM/Consensus.hs
hschain-PoW/test/TM/P2P.hs
hschain-crypto/HSChain/Crypto/Classes/Hash.hs
nix/shell.nix

- Add CryptoHashable instance for Natural
- Add more instances for Work
- Better logging
- In memory storage is moved into module in hschain-PoW since it surfaced everywhere
- Also check that mined block is correct when sending it to consensus engine

Collection of slightly related changes:

---

hschain-examples-types/HSChain/Mock/Coin/Types.hs
hschain-examples-types/HSChain/Mock/Dioxane/Types.hs
hschain-examples/HSChain/Mock.hs
hschain-examples/HSChain/Mock/Coin.hs
hschain-examples/HSChain/Mock/Dioxane.hs
hschain-examples/HSChain/Mock/KeyVal.hs
hschain-examples/HSChain/Mock/Types.hs
hschain-examples/test/TM/Integration.hs
hschain-examples/test/TM/P2P/PEX.hs
hschain-examples/test/TM/Validators.hs

Also switch to SHA256 so hashes will fit into line in BEX

Add ability to store state snapshots in the DB

---

hschain-PoW/HSChain/Examples/Simple.hs
hschain-PoW/exe/pow-node.hs
proof-of-work/cbits/evpow.c
proof-of-work/cbits/evpow.h
proof-of-work/exe/Main.hs
proof-of-work/src/HSChain/POW.hs

Изменений мало - только перестановка порядка nonce и заголовка. Ещё убрал закомментированный код.

PoW puzzle better dependence on header

---

hschain-examples/HSChain/Mock/Coin.hs
hschain-examples/exe/coin-node.hs
hschain-examples/test/TM/Mempool.hs
hschain/HSChain/Mempool.hs
hschain/HSChain/P2P/Internal.hs

Main goal of this change is to allow provide building blocks for future mempool integrated with state handling

Factor out mempool logic into pure data structure

---

hschain-examples/test/TM/Mempool.hs
hschain/HSChain/Mempool.hs

Which is necessary for mempool integrated with blockchain state managemment

Factor out mempool as data structure

---

hschain-examples-types/HSChain/Mock/Coin/Types.hs
hschain-examples-types/HSChain/Mock/Dioxane/Types.hs
hschain-merkle/HSChain/Types/Merkle/Types.hs
hschain/HSChain/Mempool.hs
hschain/HSChain/Run.hs

Now mempool filters transaction in small chunks without blocking until entire content is processed

Rework mempool as state machine. 

---

hschain-PoW/HSChain/Examples/Simple.hs
hschain-PoW/HSChain/PoW/Consensus.hs
hschain-PoW/HSChain/PoW/Node.hs
hschain-PoW/HSChain/PoW/P2P.hs
hschain-PoW/HSChain/PoW/P2P/Handler/Consensus.hs
hschain-PoW/HSChain/PoW/P2P/Handler/PEX.hs
hschain-PoW/HSChain/PoW/P2P/Handler/Peer.hs
hschain-PoW/HSChain/PoW/P2P/Types.hs
hschain-PoW/HSChain/PoW/Types.hs
hschain-PoW/exe/pow-node.hs
hschain-PoW/test/TM/Consensus.hs
hschain-PoW/test/TM/P2P.hs
hschain-PoW/test/TM/Util/Mockchain.hs

We can add transactions to consensus' state and we can invent blocks from consensus' state.
Also, there is an addition of test of slightly deeper reorganization.

Better tests; more functionality in consensus

---

hschain-crypto/HSChain/Crypto/Classes.hs

-  Wrapper for CBOR
- Explicit implementations for To/FromJSONKey

More wrapper for DerivingVia

---

hschain-PoW/HSChain/PoW/Types.hs
hschain-db/HSChain/Store/Query.hs
hschain-db/hschain-db.cabal
hschain/HSChain/Store.hs

Also add sqlite instances to Height/Time

Move newtype wrapper to hshcahin-db 

---

hschain-PoW/HSChain/Examples/Coin.hs
hschain-PoW/HSChain/PoW/Consensus.hs
hschain-PoW/HSChain/PoW/Node.hs
hschain-PoW/exe/coin-node.hs
hschain-PoW/hschain-PoW.cabal
hschain-PoW/test/TM/Store.hs
hschain-PoW/test/TM/Util/Mockchain.hs

This is port of mock coin from hschain-examples. It uses simple SHA256 puzzle. So far it only able to mine empty blocks and no state processing is implemented

First draft of PoW mock coin

---

hschain-PoW/HSChain/PoW/Node.hs
hschain-db/HSChain/Store/Query.hs
hschain-db/hschain-db.cabal

- New wrapper for ByteRepr based instances
- Functions for working with explicit encoders

Extend SQL API

---

hschain-PoW/HSChain/PoW/Consensus.hs
hschain-PoW/HSChain/PoW/P2P.hs
hschain-PoW/HSChain/PoW/P2P/Handler/Consensus.hs
hschain-PoW/HSChain/PoW/P2P/Handler/Peer.hs
hschain-PoW/hschain-PoW.cabal
hschain-PoW/test/TM/Consensus.hs
hschain-PoW/test/TM/Store.hs
hschain-control/HSChain/Control/Via.hs
hschain-control/hschain-control.cabal
hschain-db/HSChain/Store/Query.hs
hschain-db/hschain-db.cabal
hschain-examples/hschain-examples.cabal
hschain-logger/HSChain/Logger.hs
hschain-logger/hschain-logger.cabal
hschain/HSChain/Monitoring.hs
hschain/HSChain/P2P/PeerState/Handle.hs
hschain/HSChain/P2P/PeerState/Handle/Ahead.hs
hschain/HSChain/P2P/PeerState/Handle/Current.hs
hschain/HSChain/P2P/PeerState/Handle/Lagging.hs
hschain/HSChain/P2P/PeerState/Types.hs
hschain/HSChain/Store.hs
hschain/HSChain/Store/Internal/Query.hs
hschain/hschain.cabal
nix/release.nix

We get lens somewhere from dependency tree so there's little sense to sticking to microlens

Just bite the bullet and use lens everywhere

---

hschain-examples/HSChain/Mock/Coin.hs
hschain-examples/hschain-examples.cabal
hschain-mempool/HSChain/Mempool.hs

- Add -A65M to coin node rts settings
- Use of mwc-random instead of random for TX generation
- Bug fix in transaction generator
- Miscellaneous formatting

Miscelameous bug fixes and optimizations

---

hschain-db/HSChain/Store/Query.hs

This is probably simplest variant which finalizes all statements when (and only when!) connection is closed. We don't need to create/destroy statements anyway

Add support for prepared statements

---

hschain-examples/HSChain/Mock/Coin.hs
hschain-examples/test/TM/Coin.hs
hschain-examples/test/TM/Integration.hs
hschain-examples/test/TM/Util/MockChain.hs
notebook/benchmarks.ipynb

Most important changes:
- Database index for TX generation
- Use of prepared statements
- Limit size of blocks.
This allows us to get to about 1k tps but no further. That would require better  monitoring in order to uderstand what subsystem limits performance 
Also fixes bug where database backed state didn't perform context free validation on TX

Optimize performance of mock coin

---

hschain-PoW/HSChain/Examples/Coin.hs
hschain-PoW/HSChain/PoW/Mempool.hs
hschain-PoW/HSChain/PoW/Node.hs
hschain-PoW/HSChain/PoW/P2P.hs
hschain-PoW/HSChain/PoW/P2P/Handler/PEX.hs
hschain-PoW/HSChain/PoW/P2P/Handler/Peer.hs
hschain-PoW/HSChain/PoW/P2P/Types.hs
hschain-PoW/exe/coin-node.hs

This is just an sketch of an implementation

Add mempool for PoW coin

---

hschain-PoW/HSChain/PoW/Node.hs
hschain-PoW/exe-test/pow/node-any.yaml
hschain-PoW/exe-test/pow/node1.yaml
hschain-PoW/exe-test/pow/node2.yaml
hschain-PoW/exe-test/run-pow.sh
hschain-PoW/exe/coin-node.hs

Add tests for executable hschain-POW-coin and get rid of cfgPriv that unneccesarily intertwingled example and core.

Better code structure; tests for executable

---

hschain-PoW/HSChain/PoW/API.hs
hschain-PoW/HSChain/PoW/Mempool.hs
hschain-control/HSChain/Control/Channels.hs

- Old endpoint moved to /mempool/post_tx_async
- Enpoint for checking size of mempool added

Add way to check whether posted transaction is accepted by mempool 

---

hschain-PoW/HSChain/PoW/Tests.hs
hschain-PoW/hschain-PoW.cabal
hschain-PoW/test/TM/Store.hs
hschain-db/HSChain/Store/Query.hs

Also add haddocks or hschain-db

Expose generic tests in library

---

hschain-PoW/HSChain/Examples/Coin.hs
hschain-PoW/HSChain/Examples/Simple.hs
hschain-merkle/HSChain/Types/Merkle/Tree.hs
hschain-merkle/HSChain/Types/Merkle/Types.hs
hschain-merkle/hschain-merkle.cabal
hschain-merkle/test/TM/MerkleBlock.hs
hschain-quickcheck/HSChain/Arbitrary/Instances.hs
hschain-types/HSChain/Types/Blockchain.hs
hschain/HSChain/Store/Internal/BlockDB.hs

Add IsMerkleNode type class which unifies MerkleNode and merkle trees. Also pwrovide all necessary instances

Make merkle trees suitable for use
